---
title: "Análisis Exploratorio de Datos"
author: "Isaac Herranz Blasco"
date: "`r Sys.Date()`"
output: html_document
---

```{r selección muestra}
library(readxl);
library(dplyr);
library(writexl);

IE <- read_excel("union_europea_IE.xlsx");
PIB <- read_excel("union_europea_PIB.xlsx");
```
```{r}
head(PIB)
head(IE)
```


```{r Tipo variable IE}
descIE = data.frame("variable" = colnames(IE),
                    "tipo" = c('text', 'datetime', rep('text',4), rep("numerical", 2),rep('text',2)),
                    stringsAsFactors = FALSE)
descIE
```

```{r Tipo variable PIB}
descPIB = data.frame("variable" = colnames(PIB),
                    "tipo" = c('text', 'datetime', rep('text',5), rep("numerical", 2),rep('text',2)),
                    stringsAsFactors = FALSE)
descPIB
```

```{r}
# Seleccionando columnas 4 a 8 de PIB
PIB2 <- PIB[, 4:8]
# Mostrando PIB2
PIB2

# Seleccionando columnas 4 a 8 de IE
IE2 <- IE[, 4:8]
# Mostrando IE2
IE2

```

```{r Variables constantes o casi constantes}
## Numericas
IEnumeric_columns <- descIE$variable[descIE$tipo == "numerical"]
summary(IE[,IEnumeric_columns])
```
```{r Variables constantes o casi constantes}
## Numericas
PIBnumeric_columns <- descPIB$variable[descPIB$tipo == "numerical"]
summary(PIB[,PIBnumeric_columns])
```

```{r coeficiente de variacion numéricas}
# Convertir las columnas numéricas a tipo numérico (si es necesario)
numeric_columns <- descDF$variable[descDF$tipo == "numerical"]

# Asegurarse de que las columnas numéricas estén en formato numérico
df[numeric_columns] <- lapply(df[numeric_columns], as.numeric)

# Calcular la desviación estándar para las columnas numéricas
mySD <- apply(df[, numeric_columns], 2, sd, na.rm = TRUE)

# Calcular la media de las columnas numéricas
myMU <- colMeans(df[, numeric_columns], na.rm = TRUE)

# Calcular el coeficiente de variación (CV) como desviación estándar / media
myCV <- mySD / myMU

# Ordenar los resultados del coeficiente de variación
sortedCV <- sort(myCV)

# Mostrar los resultados
sortedCV

```

```{r Coeficiente de variación categóricas}
# Para las variables binarias
apply(df[,descDF$variable[descDF$tipo == "binary"]], 2, table, useNA = "i")

# Aplicando la función table para las variables categóricas
apply(df[,descDF$variable[descDF$tipo == "categorical"]], 2, table, useNA = "i")

# Calculando los porcentajes de cada categoría para las variables categóricas
resultado_categoricas <- apply(df[,descDF$variable[descDF$tipo == "categorical"]], 2,
      function(x) round(100 * table(x) / sum(table(x)), 2))

# Mostrando los resultados
print(resultado_categoricas)
```

```{r Valores Faltantes}
# Calcular el número de valores NA por columna
numNA <- apply(df, 2, function(x) sum(is.na(x)))

# Calcular el porcentaje de valores NA por columna
percNA <- round(100 * apply(df, 2, function(x) mean(is.na(x))), 2)

# Crear un data frame con los resultados
tablaNA <- data.frame("Variable" = names(df), "numNA" = numNA, "percNA" = percNA)

# Filtrar solo las columnas con valores faltantes
tablaNA_faltantes <- tablaNA[tablaNA$numNA > 0, ]

print(tablaNA_faltantes)

```

